DROP TABLE IF EXISTS TB_HEROES;
CREATE TABLE TB_HEROES (
  ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  NOME TEXT NOT NULL,
  PODER TEXT NOT NULL
)

--create
INSERT INTO TB_HEROES (NOME, PODER) 
VALUES 
    ('Flash', 'Super velocidade'),
    ('Superman', 'Super força'),
    ('Batman', 'Inteligência')

SELECT * FROM TB_HEROES;
SELECT * FROM TB_HEROES WHERE NOME = 'Batman';

--UPDATE
UPDATE TB_HEROES
SET NOME = 'Goku', PODER = 'Super Sayajin'
WHERE ID = 1;

--DELETE
DELETE FROM TB_HEROES
WHERE ID = 2;
```